# logging:
#   level: info # debug | info | warn | error
#   file: huetemps.log # absolute or relative to this config file
#   maxSize: 10m # rotate after this size
#   maxFiles: 5 # number of rotated files to keep
# temps:
#   zoneName: Hue Temps # All lights in this zone will be set to correct temp
